# Generated by Django 4.2.15 on 2024-08-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13)),
                ('CodigodeBarras', models.CharField(max_length=100)),
                ('NoTopografico', models.CharField(max_length=100)),
                ('Titulo', models.CharField(max_length=200)),
                ('Autor', models.CharField(max_length=200)),
                ('Ciudad', models.CharField(max_length=100)),
                ('Editorial', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Edicion', models.CharField(max_length=50)),
                ('Pagsovols', models.IntegerField()),
                ('Ejemplares', models.IntegerField()),
                ('Genero', models.CharField(max_length=100)),
                ('Ubicacion', models.CharField(max_length=100)),
            ],
        ),
    ]
